### ISSUE TITLE
Error on getting String Table

### ISSUE THREAD

**Issue by starFelix** [DeVaukz/MachO-Kit#11]
![_15358871318763](https://user-images.githubusercontent.com/5734060/44955406-4ef19880-aee5-11e8-892d-ffdbb73d68eb.png)
I'm trying to analysis a MachO file like above. But when I want to get the info of `String Table` , I got an error said `Image does not have a __LINKEDIT segment.`. Obviously, there is a `__LINKEDIT segment` on this file.

**Comment by DeVaukz** [comment]
Can I get the Mach-O file from somewhere?

**Comment by starFelix** [comment]
[ErrorSubProject.zip](https://github.com/DeVaukz/MachO-Kit/files/2343968/ErrorSubProject.zip)
This is the file.

**Comment by DeVaukz** [comment]
[Mach-O Explorer](https://github.com/DeVaukz/MachO-Explorer) does not encounter any trouble loading the string table for that file.

I also wrote a small test playground:
```
    let memoryMap = try! MKMemoryMap(contentsOfFile: URL(fileURLWithPath: "/Users/Shared/ErrorSubProject"))
    let macho = try! MKMachOImage(name: "ErrorSubProject", flags: .init(rawValue: 0), atAddress: mk_vm_address_t(0), inMapping: memoryMap)
    
    if let stringTable = macho.stringTable.value {
        print("Found string table.  It contains \(stringTable.strings.count) strings")
    } else {
        print("Error retrieving string table: \(macho.stringTable.error)")
    }
```

It prints:

```
Found string table.  It contains 50 strings
```

Do you have the latest Mach-O Kit code?

**Comment by starFelix** [comment]
After comparting to my code, I found that I set `flags` to 1. Maybe the code resulted to an error. I have changed it to 0, and It works. Thank you .
