### ISSUE TITLE
Replace @import with #import for support of .mm files

### ISSUE THREAD

**Issue by ghost** [DeVaukz/MachO-Kit#12]
Hi, I've created empty project, loaded MachO-Kit framework in it, and included **#import <MachOKit/MachOKit.h>** into my .m file.

Everything was fine until I changed extension to .mm.
As I found out, there are some troubles with importing libraries via @import while using C++.
I've been trying a bunch of stuff, e.g. passing flags -fmodules and -fcxx-modules, but nothing helped.

Later, I've found out that the fix is to replace all entries of **@import Foundation** into **#import <Foundation/Foundation.h>** in MachO-Kit.
After this changes, everything works fine(it builds and I'm still able to parse MachO files even with .mm extenstion).

Will this change broke something?
If there is no problems with it, could you please apply fix?

**Comment by DeVaukz** [comment]
Fixed with ee46e3d3bd6a72d358093b72cd5480393dc632b4

Thanks
