### ISSUE TITLE
Any chance to support CocoaPods?

### ISSUE THREAD

**Issue by k06a** [DeVaukz/MachO-Kit#2]
Awesome project 😉

**Comment by DeVaukz** [comment]
I don't use CocoaPods myself but if somebody wants to submit a PR with a Pods file, I'll merge it.

**Comment by k06a** [comment]
Fine, I'll try

**Comment by k06a** [comment]
@DeVaukz can you please add any git tag, for example `0.1.0` to the top commit?

**Comment by DeVaukz** [comment]
Done.  Thanks!
