### ISSUE TITLE
__cfstring Section

### ISSUE THREAD

**Issue by haltepunkt** [DeVaukz/MachO-Kit#9]
Is the **__DATA** segment's **__cfstring** section not implemented? Please excuse me if I'm missing something obvious.

I'd like to parse this section's **CFString** elements.

**Comment by DeVaukz** [comment]
Not yet.

**Comment by haltepunkt** [comment]
I'm looking forward to using the implementation!

Right now I'm copying the **__cfstring** section's bytes from the memory map into a buffer and parse the **CFString** structs.

```
struct CFString {
  const int *isa;
  int flags;
  const char *str;
  long length;
};
```

cfString->str then points to a string that is inside the **__cstring** section. Such string is easily parsed by using the **MKCStringSection** implementation.

**Comment by DeVaukz** [comment]
Initial implementation done in 5d75c52a0db9df0e9e2c8cffb3c588f3b1dff385.  I will clean it up later to handle the more esoteric representations for constant CFStrings (UTF-16).

Example Usage:
```
    let memoryMap = try! MKMemoryMap(contentsOfFile: URL(fileURLWithPath: "/Applications/Calculator.app/Contents/MacOS/Calculator"))
    let macho = try! MKMachOImage(name: "Dock", flags: .init(rawValue: 0), atAddress: mk_vm_address_t(0), inMapping: memoryMap)
    
    let cfStringsSection = macho.sections(withName: "__cfstring", in: nil).first as! MKCFStringsSection
    for cfstring in cfStringsSection.strings {
        let cString = cfstring.string.pointee
        if let cStringValue = cString.value {
            print("Found string: \(cStringValue)")
        }
    }
```

**Comment by haltepunkt** [comment]
Thank you very much!
